# Generated by Django 4.2.7 on 2024-01-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("date_entree", models.DateField()),
                ("date_livraison", models.DateField()),
                ("note_livreur", models.IntegerField()),
                ("note_gestionnaire", models.IntegerField()),
                ("nom_client", models.CharField(max_length=100)),
                ("tel_client", models.CharField(max_length=15)),
                ("region", models.CharField(max_length=50)),
                ("adresse", models.TextField()),
                ("nom_produit", models.CharField(max_length=100)),
                ("unite", models.CharField(max_length=20)),
                ("prix_propose", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "frais_livraison",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("gains", models.DecimalField(decimal_places=2, max_digits=10)),
                ("etat_livraison", models.CharField(max_length=20)),
                ("soldee", models.BooleanField()),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("url_order", models.URLField()),
            ],
        ),
    ]
